---
- hosts: all
  gather_facts: false
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    group: "admin"
    key_path: ./keys/{{ item }}_key
    users:
      - ["rpolnx"]

  tasks:
    - name: Generate ssh keys
      become: false
      community.crypto.openssh_keypair:
        path: "{{ key_path }}"
        comment: "{{ item }}"
      with_items: "{{ users }}"
      when: inventory_hostname in groups['local']

    - debug:
        msg: "{{ lookup('file', key_path ) | md5}}"
      with_items: "{{ users }}"
      when: inventory_hostname in groups['local']

    - name: Create group "{{ group }}"
      group:
        name: "{{ group }}"
        state: present

    - name: Allow {{ group }} group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^%{{ group }}"
        line: "%{{ group }} ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"

    - name: Creating users
      user:
        name: "{{ item }}"
        groups: "{{ group }}"
        shell: /bin/bash
        append: yes
        state: present
        # password: "{{ password }}" # will use ssh
      with_items: "{{ users }}"

    - name: "Add authorized keys"
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', key_path + '.pub') }}"
      with_items: "{{ users }}"

