version: '3.8'
services:
  mongodb:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    restart: always
    ports:
      - 27016:27016
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
