version: '3.8'
services:
  mongodb:
    image: mongo:4.2
    restart: always
    ports:
      - 27016:27016
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
